#!/bin/sh
#export shell folder
export PATH="$PATH:~/Documents/Shell"

#alias
alias alidocker="export DOCKER_TLS_VERIFY=1;export DOCKER_HOST='tcp://cn.simcu.com:65535'"
alias jpdocker="export DOCKER_TLS_VERIFY=1;export DOCKER_HOST='tcp://jp.simcu.com:65535'"
alias dme="eval $(docker-machine env)"

#编辑器 切换HOSTS
alias edit="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias chdev="sudo sed -i '' -e '/192.168.64..*/d' /etc/hosts;cat /etc/hosts.dev >> /etc/hosts"
alias chnor="sudo sed -i '' -e '/192.168.64..*/d' /etc/hosts"
alias ehdev="edit /etc/hosts.dev"
alias ehnor="edit /etc/hosts"
alias lhdev="cat /etc/hosts.dev"
alias lhnor="cat /etc/hosts"
alias ahdev="echo `docker-machine ip default` $1 >> /etc/hosts.dev"
alias ahnor="echo $1 $2 >> /etc/hosts"
alias ealias="edit ~/Documents/Shell" 